version: '3'
services:
  lsst:
    container_name: lsst
    image: leanne/lsst-stack
    restart: unless-stopped
    volumes:
      - type: bind
        source: /Users/leanne/LSST/pycharm-workspace
        target: /mnt/repos
        read_only: false
      - type: bind
        source: /Users/leanne/Datasets
        target: /mnt/datasets
        read_only: false

    tty: true
    stdin_open: true